# Generated by Django 5.1.5 on 2025-02-02 00:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReg',
            fields=[
                ('clinic_code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('clinic_name', models.CharField(max_length=8)),
                ('mobile_number', models.CharField(max_length=11)),
                ('reg_date_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('member', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('other_specializations_id', models.ManyToManyField(to='Clinic.specialization')),
            ],
        ),
    ]
