# Generated by Django 5.1.5 on 2025-02-02 01:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='town_near',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='patient_id',
            new_name='national_id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='registration_number',
            field=models.CharField(default=uuid.uuid4, max_length=50, null=True),
        ),
    ]
