# Generated by Django 5.1.5 on 2025-01-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_next_of_kin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_Doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_Member_Patient',
        ),
        migrations.RemoveField(
            model_name='user',
            name='patient_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], default='patient', error_messages={'required': 'Role must be provided'}, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=10),
        ),
    ]
