# Generated by Django 5.1.5 on 2025-02-02 00:11

import Clinic.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('soshi_user', models.CharField(max_length=100)),
                ('blog_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=250)),
                ('blog_subtitle', models.CharField(max_length=250)),
                ('caption', models.CharField(max_length=3000)),
                ('blog_image', models.ImageField(default='icon/bondijunction_dentalclinic_logo-300x258.jpg', upload_to='profile_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagetitle', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('aboutus', models.TextField()),
                ('email', models.EmailField(max_length=200)),
                ('mobilenumber', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(default=Clinic.models.generate_service_id, max_length=6, null=True)),
                ('sname', models.CharField(max_length=100, null=True)),
                ('service_title', models.CharField(max_length=225, null=True)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='services_image/')),
                ('service_logo', models.ImageField(blank=True, null=True, upload_to='service_logo/')),
                ('service_price', models.IntegerField(null=True)),
                ('ratings', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
